# syntax=docker/dockerfile-upstream:master-labs
FROM debian:stable-slim as hsl-builder

ADD https://github.com/WizOfOx/hsl.git /src

RUN apt update && \
    apt install -y build-essential gfortran

WORKDIR /src

RUN ./configure --prefix=/build && \
    make && \
    make install