# syntax=docker/dockerfile-upstream:master-labs
FROM debian:stable-slim as hsl-builder

ARG ACCESS_TOKEN

RUN apt update && \
    apt install -y build-essential gfortran git

RUN  git clone ${ACCESS_TOKEN}@github.com/WizOfOx/hsl.git /src


WORKDIR /src

RUN ./configure --prefix=/build && \
    make && \
    make install