name: HSL-Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Builds
      uses: actions/checkout@v2.6.0
      with:
        repository: WizOfOx/Builds
        path: builds
    - name: Checkout HSL
      uses: actions/checkout@v2.6.0
      with:
        repository: WizOfOx/hsl
        path: hsl
        ref: master
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_HUB }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.2.0
      with:
        filename: ${{ env.GITHUB_WORKSPACE }}/builds/Dockerfile.hsl
        push: true
        tags: hsl
        
